In [3]:
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
df=pd.read_csv("Data file.csv")

In [5]:
df

        Unnamed: 0  label       msisdn     aon  daily_decr30  daily_decr90  rental30  rental90  last_rech_date_ma  last_rech_date_da  last_rech_amt_ma  cnt_ma_rech30  fr_ma_rech30  sumamnt_ma_rech30  medianamnt_ma_rech30  medianmarechprebal30  cnt_ma_rech90  fr_ma_rech90  sumamnt_ma_rech90  medianamnt_ma_rech90  medianmarechprebal90  cnt_da_rech30  fr_da_rech30  cnt_da_rech90  fr_da_rech90  cnt_loans30  amnt_loans30  maxamnt_loans30  medianamnt_loans30  cnt_loans90  amnt_loans90  maxamnt_loans90  medianamnt_loans90  payback30  payback90 pcircle       pdate
0                1      0  21408I70789   272.0   3055.050000   3065.150000    220.13    260.13                2.0                0.0              1539              2          21.0             3078.0                1539.0                  7.50              2            21               3078                1539.0                  7.50            0.0           0.0              0             0            2            12              6.0                 0.0          2.0            12                6                 0.0  29.000000  29.000000     UPW  2016-07-20
1                2      1  76462I70374   712.0  12122.000000  12124.750000   3691.26   3691.26               20.0                0.0              5787              1           0.0             5787.0                5787.0                 61.04              1             0               5787                5787.0                 61.04            0.0           0.0              0             0            1            12             12.0                 0.0          1.0            12               12                 0.0   0.000000   0.000000     UPW  2016-08-10
2                3      1  17943I70372   535.0   1398.000000   1398.000000    900.13    900.13                3.0                0.0              1539              1           0.0             1539.0                1539.0                 66.32              1             0               1539                1539.0                 66.32            0.0           0.0              0             0            1             6              6.0                 0.0          1.0             6                6                 0.0   0.000000   0.000000     UPW  2016-08-19
3                4      1  55773I70781   241.0     21.228000     21.228000    159.42    159.42               41.0                0.0               947              0           0.0                0.0                   0.0                  0.00              1             0                947                 947.0                  2.50            0.0           0.0              0             0            2            12              6.0                 0.0          2.0            12                6                 0.0   0.000000   0.000000     UPW  2016-06-06
4                5      1  03813I82730   947.0    150.619333    150.619333   1098.90   1098.90                4.0                0.0              2309              7           2.0            20029.0                2309.0                 29.00              8             2              23496                2888.0                 35.00            0.0           0.0              0             0            7            42              6.0                 0.0          7.0            42                6                 0.0   2.333333   2.333333     UPW  2016-06-22
...            ...    ...          ...     ...           ...           ...       ...       ...                ...                ...               ...            ...           ...                ...                   ...                   ...            ...           ...                ...                   ...                   ...            ...           ...            ...           ...          ...           ...              ...                 ...          ...           ...              ...                 ...        ...        ...     ...         ...
209588      209589      1  22758I85348   404.0    151.872333    151.872333   1089.19   1089.19                1.0                0.0              4048              3           2.0            10404.0                3178.0                 91.81              3             2              10404                3178.0                 91.81            0.0           0.0              0             0            2            12              6.0                 0.0          2.0            12                6                 0.0   1.000000   1.000000     UPW  2016-06-17
209589      209590      1  95583I84455  1075.0     36.936000     36.936000   1728.36   1728.36                4.0                0.0               773              4           1.0             3092.0                 773.0                161.30              6             2               4038                 773.0                111.80            0.0           0.0              0             0            3            18              6.0                 0.0          3.0            18                6                 0.0   1.000000   1.000000     UPW  2016-06-12
209590      209591      1  28556I85350  1013.0  11843.111667  11904.350000   5861.83   8893.20                3.0                0.0              1539              5           8.0             9334.0                1539.0                 51.13             11             5              18592                1539.0                 47.13            0.0           0.0              0             0            4            42             12.0                 0.0          6.0            54               12                 0.0   4.000000   3.833333     UPW  2016-07-29
209591      209592      1  59712I82733  1732.0  12488.228333  12574.370000    411.83    984.58                2.0               38.0               773              5           4.0            12154.0                 773.0                164.00              6             4              17941                2410.5                100.00            0.0           0.0              1             0            2            18             12.0                 0.0          3.0            24               12                 0.0   0.000000  10.500000     UPW  2016-07-25
209592      209593      1  65061I85339  1581.0   4489.362000   4534.820000    483.92    631.20               13.0                0.0              7526              2           1.0             9065.0                4532.5                356.70              3            19              16591                7526.0                392.20            0.0           0.0              0             0            2            18             12.0                 0.0          2.0            18               12                 0.0   0.000000   0.000000     UPW  2016-07-07

[209593 rows x 37 columns]

In [6]:
df.describe()

          Unnamed: 0          label            aon   daily_decr30   daily_decr90       rental30       rental90  last_rech_date_ma  last_rech_date_da  last_rech_amt_ma  cnt_ma_rech30   fr_ma_rech30  sumamnt_ma_rech30  medianamnt_ma_rech30  medianmarechprebal30  cnt_ma_rech90   fr_ma_rech90  sumamnt_ma_rech90  medianamnt_ma_rech90  medianmarechprebal90  cnt_da_rech30   fr_da_rech30  cnt_da_rech90   fr_da_rech90    cnt_loans30   amnt_loans30  maxamnt_loans30  medianamnt_loans30    cnt_loans90   amnt_loans90  maxamnt_loans90  medianamnt_loans90      payback30      payback90
count  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000      209593.000000      209593.000000     209593.000000  209593.000000  209593.000000      209593.000000         209593.000000         209593.000000   209593.00000  209593.000000      209593.000000         209593.000000         209593.000000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000    209593.000000       209593.000000  209593.000000  209593.000000    209593.000000       209593.000000  209593.000000  209593.000000
mean   104797.000000       0.875177    8112.343445    5381.402289    6082.515068    2692.581910    3483.406534        3755.847800        3712.202921       2064.452797       3.978057    3737.355121        7704.501157           1812.817952           3851.927942        6.31543       7.716780       12396.218352           1864.595821             92.025541     262.578110    3749.494447       0.041495       0.045712       2.758981      17.952021       274.658747            0.054029      18.520919      23.645398         6.703134            0.046077       3.398826       4.321485
std     60504.431823       0.330519   75696.082531    9220.623400   10918.812767    4308.586781    5770.461279       53905.892230       53374.833430       2370.786034       4.256090   53643.625172       10139.621714           2070.864620          54006.374433        7.19347      12.590251       16857.793882           2081.680664            369.215658    4183.897978   53885.414979       0.397556       0.951386       2.554502      17.379741      4245.264648            0.218039     224.797423      26.469861         2.103864            0.200692       8.813729      10.308108
min         1.000000       0.000000     -48.000000     -93.012667     -93.012667  -23737.140000  -24720.580000         -29.000000         -29.000000          0.000000       0.000000       0.000000           0.000000              0.000000           -200.000000        0.00000       0.000000           0.000000              0.000000           -200.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000         0.000000            0.000000       0.000000       0.000000         0.000000            0.000000       0.000000       0.000000
25%     52399.000000       1.000000     246.000000      42.440000      42.692000     280.420000     300.260000           1.000000           0.000000        770.000000       1.000000       0.000000        1540.000000            770.000000             11.000000        2.00000       0.000000        2317.000000            773.000000             14.600000       0.000000       0.000000       0.000000       0.000000       1.000000       6.000000         6.000000            0.000000       1.000000       6.000000         6.000000            0.000000       0.000000       0.000000
50%    104797.000000       1.000000     527.000000    1469.175667    1500.000000    1083.570000    1334.000000           3.000000           0.000000       1539.000000       3.000000       2.000000        4628.000000           1539.000000             33.900000        4.00000       2.000000        7226.000000           1539.000000             36.000000       0.000000       0.000000       0.000000       0.000000       2.000000      12.000000         6.000000            0.000000       2.000000      12.000000         6.000000            0.000000       0.000000       1.666667
75%    157195.000000       1.000000     982.000000    7244.000000    7802.790000    3356.940000    4201.790000           7.000000           0.000000       2309.000000       5.000000       6.000000       10010.000000           1924.000000             83.000000        8.00000       8.000000       16000.000000           1924.000000             79.310000       0.000000       0.000000       0.000000       0.000000       4.000000      24.000000         6.000000            0.000000       5.000000      30.000000         6.000000            0.000000       3.750000       4.500000
max    209593.000000       1.000000  999860.755168  265926.000000  320630.000000  198926.110000  200148.110000      998650.377733      999171.809410      55000.000000     203.000000  999606.368132      810096.000000          55000.000000         999479.419319      336.00000      88.000000      953036.000000          55000.000000          41456.500000   99914.441420  999809.240107      38.000000      64.000000      50.000000     306.000000     99864.560864            3.000000    4997.517944     438.000000        12.000000            3.000000     171.500000     171.500000

In [12]:
data=df[['daily_decr30', 'daily_decr90', 'rental30', 'rental90', 'last_rech_amt_ma', 'cnt_ma_rech30',
         'fr_ma_rech30', 'cnt_ma_rech90', 'cnt_loans30', 'amnt_loans30', 'cnt_loans90', 'amnt_loans90',
         'payback30', 'payback90']]

In [13]:
data.describe()

        daily_decr30   daily_decr90       rental30       rental90  last_rech_amt_ma  cnt_ma_rech30   fr_ma_rech30  cnt_ma_rech90    cnt_loans30   amnt_loans30    cnt_loans90   amnt_loans90      payback30      payback90
count  209593.000000  209593.000000  209593.000000  209593.000000     209593.000000  209593.000000  209593.000000   209593.00000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000  209593.000000
mean     5381.402289    6082.515068    2692.581910    3483.406534       2064.452797       3.978057    3737.355121        6.31543       2.758981      17.952021      18.520919      23.645398       3.398826       4.321485
std      9220.623400   10918.812767    4308.586781    5770.461279       2370.786034       4.256090   53643.625172        7.19347       2.554502      17.379741     224.797423      26.469861       8.813729      10.308108
min       -93.012667     -93.012667  -23737.140000  -24720.580000          0.000000       0.000000       0.000000        0.00000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000
25%        42.440000      42.692000     280.420000     300.260000        770.000000       1.000000       0.000000        2.00000       1.000000       6.000000       1.000000       6.000000       0.000000       0.000000
50%      1469.175667    1500.000000    1083.570000    1334.000000       1539.000000       3.000000       2.000000        4.00000       2.000000      12.000000       2.000000      12.000000       0.000000       1.666667
75%      7244.000000    7802.790000    3356.940000    4201.790000       2309.000000       5.000000       6.000000        8.00000       4.000000      24.000000       5.000000      30.000000       3.750000       4.500000
max    265926.000000  320630.000000  198926.110000  200148.110000      55000.000000     203.000000  999606.368132      336.00000      50.000000     306.000000    4997.517944     438.000000     171.500000     171.500000